version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: ["npm", "run", "start"]

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=name
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    command: ["java", "-jar", "/app/my-app.jar"]

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lennud
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: tmpfs
