version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: ["npm", "run", "start"]

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/lennud
      - SPRING_DATASOURCE_USERNAME=name
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    command: ["java", "-jar", "/app/Backend-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lennud
    
